import { LoginComponent } from "@src/components/Login";
import Navbar from "@src/components/Navbar";
import { useCycle } from "framer-motion";
import { Poppins } from "next/font/google";
import Head from "next/head";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const Login = () => {
  const [isOpen, toggleOpen] = useCycle(false, true);

  return (
    <>
      <Head>
        <title>Login - JAC SAC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`font-poppins ${poppins.className}`}>
        <Navbar isOpen={isOpen} toggle={() => toggleOpen()} />
        <LoginComponent />
      </main>
    </>
  );
};

export default Login;
